# Generated by Django 5.1.3 on 2024-11-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_cook_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="years_of_experience",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
